In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

In [2]:
raw_train = pd.read_csv('train.csv')
raw_test = pd.read_csv('test.csv')

In [3]:
raw_train.head(1)

Loan_ID Gender Married Dependents Education Self_Employed  \
0  LP001002   Male      No          0  Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y

In [4]:
raw_train.shape

(614, 13)

In [5]:
raw_train.nunique()

Loan_ID              614
Gender                 2
Married                2
Dependents             4
Education              2
Self_Employed          2
ApplicantIncome      505
CoapplicantIncome    287
LoanAmount           203
Loan_Amount_Term      10
Credit_History         2
Property_Area          3
Loan_Status            2
dtype: int64

In [6]:
train_df=raw_train.copy()
test_df=raw_test.copy()

In [7]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [8]:
test_df.info() #only for prediction

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 362 entries, 0 to 361
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            362 non-null    object 
 1   Gender             351 non-null    object 
 2   Married            362 non-null    object 
 3   Dependents         353 non-null    object 
 4   Education          362 non-null    object 
 5   Self_Employed      339 non-null    object 
 6   ApplicantIncome    362 non-null    int64  
 7   CoapplicantIncome  362 non-null    int64  
 8   LoanAmount         362 non-null    int64  
 9   Loan_Amount_Term   356 non-null    float64
 10  Credit_History     333 non-null    float64
 11  Property_Area      362 non-null    object 
dtypes: float64(2), int64(3), object(7)
memory usage: 34.1+ KB


In [9]:
train_y=train_df['Loan_Status'].copy()

In [10]:
train_df.drop(columns=['Loan_Status'],inplace=True)

In [11]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
dtypes: float64(4), int64(1), object(7)
memory usage: 57.7+ KB


In [12]:
train_df.drop(columns=['Loan_ID'],inplace=True)
test_df.drop(columns=['Loan_ID'],inplace=True)

In [13]:
train_df.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')

In [14]:
#Duplication check
train_df[train_df.duplicated()]

Empty DataFrame
Columns: [Gender, Married, Dependents, Education, Self_Employed, ApplicantIncome, CoapplicantIncome, LoanAmount, Loan_Amount_Term, Credit_History, Property_Area]
Index: []

In [15]:
test_df[test_df.duplicated()]

Gender Married Dependents Education Self_Employed  ApplicantIncome  \
192   Male      No          0  Graduate           Yes             5833   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
192                  0         116             360.0             1.0   

    Property_Area  
192         Urban

In [16]:
test_df.shape

(362, 11)

In [17]:
test_df.drop_duplicates(inplace=True)

In [18]:
test_df[test_df.duplicated()]

Empty DataFrame
Columns: [Gender, Married, Dependents, Education, Self_Employed, ApplicantIncome, CoapplicantIncome, LoanAmount, Loan_Amount_Term, Credit_History, Property_Area]
Index: []

In [19]:
#Missing Value analysis
train_df.isna().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
dtype: int64

In [20]:
#Impute
#Numeric-->mean
#Categorical-->mode

In [21]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             601 non-null    object 
 1   Married            611 non-null    object 
 2   Dependents         599 non-null    object 
 3   Education          614 non-null    object 
 4   Self_Employed      582 non-null    object 
 5   ApplicantIncome    614 non-null    int64  
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         592 non-null    float64
 8   Loan_Amount_Term   600 non-null    float64
 9   Credit_History     564 non-null    float64
 10  Property_Area      614 non-null    object 
dtypes: float64(4), int64(1), object(6)
memory usage: 52.9+ KB


In [22]:
train_df.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')

In [23]:
train_df.nunique()

Gender                 2
Married                2
Dependents             4
Education              2
Self_Employed          2
ApplicantIncome      505
CoapplicantIncome    287
LoanAmount           203
Loan_Amount_Term      10
Credit_History         2
Property_Area          3
dtype: int64

In [24]:
num_cols=['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term']

In [25]:
category_cols=['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed','Credit_History', 'Property_Area']

In [26]:
cat_imputer=SimpleImputer(strategy='most_frequent')
cat_imputer.fit(train_df[category_cols])

train_df[category_cols]=cat_imputer.transform(train_df[category_cols])
test_df[category_cols]=cat_imputer.transform(test_df[category_cols])

In [27]:
num_imputer=SimpleImputer(strategy='mean')
num_imputer.fit(train_df[num_cols])

train_df[num_cols]=num_imputer.transform(train_df[num_cols])
test_df[num_cols]=num_imputer.transform(test_df[num_cols])

In [28]:
train_df.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male      No          0      Graduate            No           5849.0   
1   Male     Yes          1      Graduate            No           4583.0   
2   Male     Yes          0      Graduate           Yes           3000.0   
3   Male     Yes          0  Not Graduate            No           2583.0   
4   Male      No          0      Graduate            No           6000.0   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term Credit_History  \
0                0.0  146.412162             360.0            1.0   
1             1508.0  128.000000             360.0            1.0   
2                0.0   66.000000             360.0            1.0   
3             2358.0  120.000000             360.0            1.0   
4                0.0  141.000000             360.0            1.0   

  Property_Area  
0         Urban  
1         Rural  
2         Urban  
3         Urban  
4         Urban

In [29]:
#preprocessing as per domain knowledge
train_df['ApplicantIncome']=train_df['ApplicantIncome']+train_df['CoapplicantIncome']

In [30]:
test_df['ApplicantIncome']=test_df['ApplicantIncome']+test_df['CoapplicantIncome']

In [31]:
train_df.drop(columns='CoapplicantIncome',inplace=True)
test_df.drop(columns='CoapplicantIncome',inplace=True)

In [32]:
train_df.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male      No          0      Graduate            No           5849.0   
1   Male     Yes          1      Graduate            No           6091.0   
2   Male     Yes          0      Graduate           Yes           3000.0   
3   Male     Yes          0  Not Graduate            No           4941.0   
4   Male      No          0      Graduate            No           6000.0   

   LoanAmount  Loan_Amount_Term Credit_History Property_Area  
0  146.412162             360.0            1.0         Urban  
1  128.000000             360.0            1.0         Rural  
2   66.000000             360.0            1.0         Urban  
3  120.000000             360.0            1.0         Urban  
4  141.000000             360.0            1.0         Urban

In [33]:
train_df.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History',
       'Property_Area'],
      dtype='object')

In [34]:
#Application of Label Encoder
train_df.nunique()

Gender                2
Married               2
Dependents            4
Education             2
Self_Employed         2
ApplicantIncome     554
LoanAmount          204
Loan_Amount_Term     11
Credit_History        2
Property_Area         3
dtype: int64

In [35]:
train_df["Dependents"].unique() #Ordinal data --> label encoder


array(['0', '1', '2', '3+'], dtype=object)

In [36]:
train_df["Property_Area"].unique() 

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [37]:
for col in category_cols:
    le=LabelEncoder()
    train_df[col]=le.fit_transform(train_df[col])#<-This method is used when you want to fit the scaler to the data and then transform the data using the fitted scaler in one step.
    test_df[col]=le.transform(test_df[col])#<- This method is used to transform the data using a previously fitted scaler.

In [38]:
num_cols.remove("CoapplicantIncome")

In [39]:
#log transformation
train_df[num_cols]=np.log(train_df[num_cols])

In [40]:
train_df.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0           0          0              0         8.674026   
1       1        1           1          0              0         8.714568   
2       1        1           0          0              1         8.006368   
3       1        1           0          1              0         8.505323   
4       1        0           0          0              0         8.699515   

   LoanAmount  Loan_Amount_Term  Credit_History  Property_Area  
0    4.986426          5.886104               1              2  
1    4.852030          5.886104               1              0  
2    4.189655          5.886104               1              2  
3    4.787492          5.886104               1              2  
4    4.948760          5.886104               1              2

In [41]:
#scaling
minmax=MinMaxScaler()
train_df=minmax.fit_transform(train_df)
test_df=minmax.transform(test_df)

In [42]:
#Building the Model
from sklearn.model_selection import train_test_split


In [43]:
X_train, X_test, y_train, y_test = train_test_split(train_df, train_y, test_size=0.3, random_state=0)

In [44]:
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()
log.fit(X_train,y_train)

LogisticRegression()

In [45]:
y_pred_test=log.predict(X_test)

In [46]:
from sklearn.metrics import accuracy_score

In [47]:
acc=accuracy_score(y_test,y_pred_test)
print(f"Accracy is {acc}")

Accracy is 0.827027027027027


In [48]:
#serialization & deserialization
import joblib
joblib.dump(log,"my_trained_model_v1.pkl")

['my_trained_model_v1.pkl']

In [49]:
final_model=joblib.load("my_trained_model_v1.pkl")

In [50]:
final_model

LogisticRegression()

In [51]:
final_model.intercept_,final_model.coef_

(array([-2.05782461]),
 array([[ 0.02382467,  0.35479553,  0.39528663, -0.442547  , -0.04913972,
          0.04022649, -0.81819713,  0.23511056,  3.18026394,  0.22583306]]))

In [52]:
log.intercept_,log.coef_

(array([-2.05782461]),
 array([[ 0.02382467,  0.35479553,  0.39528663, -0.442547  , -0.04913972,
          0.04022649, -0.81819713,  0.23511056,  3.18026394,  0.22583306]]))

# Package and Modules

In [53]:
import PackageA

In [54]:
from PackageA import f1

In [55]:
f1.print_something()

'output from f1'

In [56]:
from PackageA import f2

In [57]:
f2.print_something()

'output from f2'

In [58]:
from PackageA.f1 import print_something as flp
flp()

'output from f1'

In [59]:
from PackageA.SubPackageA import f3

In [60]:
f3.print_something()

'output from f3'

In [61]:
from PackageA.SubPackageB import f5
f5.print_something()

'output from f5'

In [62]:
from PackageA.SubPackageB import f5
f5.print_something()

'output from f5'

In [63]:
import sys

In [64]:
sys.path

['C:\\Users\\WhiyongL\\Desktop\\MLOPs practice\\packaging ML model',
 'C:\\Users\\WhiyongL\\AppData\\Local\\anaconda3\\python311.zip',
 'C:\\Users\\WhiyongL\\AppData\\Local\\anaconda3\\DLLs',
 'C:\\Users\\WhiyongL\\AppData\\Local\\anaconda3\\Lib',
 'C:\\Users\\WhiyongL\\AppData\\Local\\anaconda3',
 '',
 'C:\\Users\\WhiyongL\\AppData\\Local\\anaconda3\\Lib\\site-packages',
 'C:\\Users\\WhiyongL\\AppData\\Local\\anaconda3\\Lib\\site-packages\\win32',
 'C:\\Users\\WhiyongL\\AppData\\Local\\anaconda3\\Lib\\site-packages\\win32\\lib',
 'C:\\Users\\WhiyongL\\AppData\\Local\\anaconda3\\Lib\\site-packages\\Pythonwin']

In [65]:
sys.path.append('C:\\path\\to\\dir')#adding custome path

# Getting the parent directory

In [66]:
import PackageA
import pathlib
pathlib.Path(PackageA.__file__)

WindowsPath('C:/Users/WhiyongL/Desktop/MLOPs practice/packaging ML model/PackageA/__init__.py')

In [67]:
pathlib.Path(PackageA.__file__).resolve().parent

WindowsPath('C:/Users/WhiyongL/Desktop/MLOPs practice/packaging ML model/PackageA')

# Create Custome Data Transformers

In [ ]:
#key thing --> Inherit - BaseEstimator, TransformerMixin
#implement fit and transform
#accept input with initmethod

In [68]:
from sklearn.base import BaseEstimator,TransformerMixin

class DemoTransformer(BaseEstimator, TransformerMixin):
    def __init__(self):
        pass

    def fit(self,X,y=None):
        return self

    def transform(self,X):
        return X

In [73]:
DemoTransformer.fit(BaseEstimator,1)

sklearn.base.BaseEstimator

In [72]:
DemoTransformer.transform(BaseEstimator,1)

1

In [74]:
from sklearn.base import BaseEstimator,TransformerMixin
class MeanImputer(BaseEstimator, TransformerMixin):
    def __init__(self,variables=None):
        self.variables=variables

    def fit(self,X,y=None):
        self.mean_dict={}
        for col in self.variables:
            self.mean_dict[col]=X[col].mean()
        return self

    def transform(self,X):
        X=X.copy()
        for col in self.variables:
            X[col].fillna(self.mean_dict[col],inplace=True)
        return X

In [76]:
np.random.seed(0)
df=pd.DataFrame(np.random.randint(0,110,(10,2)),columns=["A","B"])
df.iloc[1,0]=np.nan
df.iloc[2,1]=np.nan
df.iloc[3,1]=np.nan
df

A      B
0  44.0   47.0
1   NaN   67.0
2  67.0    NaN
3   9.0    NaN
4  21.0   36.0
5  87.0   70.0
6  88.0   88.0
7  12.0   58.0
8  65.0  102.0
9  39.0   87.0

In [77]:
mean_imputer=MeanImputer(variables=['A','B'])

In [80]:
mean_imputer.fit(df)

MeanImputer(variables=['A', 'B'])

In [81]:
mean_imputer.mean_dict

{'A': 48.0, 'B': 69.375}

In [82]:
df.mean()

A    48.000
B    69.375
dtype: float64

In [83]:
mean_imputer.transform(df)

A        B
0  44.0   47.000
1  48.0   67.000
2  67.0   69.375
3   9.0   69.375
4  21.0   36.000
5  87.0   70.000
6  88.0   88.000
7  12.0   58.000
8  65.0  102.000
9  39.0   87.000

In [1]:
import numpy
numpy.__version__

'1.26.4'

In [2]:
import pandas
pandas.__version__

'2.1.4'

In [3]:
import joblib
joblib.__version__

'1.2.0'

In [4]:
import sklearn
sklearn.__version__

'1.2.2'

In [5]:
import scipy
scipy.__version__

'1.11.4'

In [6]:
import setuptools#required for package building
setuptools.__version__

'68.2.2'

In [7]:
import wheel
wheel.__version__

'0.41.2'

In [1]:
import sys
print(sys.version)


3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]
